services:
  - type: web
    name: safety-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
